### ISSUE TITLE
Implement multi-client end-to-end tests

### ISSUE THREAD

**Issue by stafyniaksacha** [kuzzleio/kuzzle-test-environment#3] opened 2017-03-22 17:17 UTC
Once [multi-client test stack](https://github.com/kuzzleio/kuzzle-client-tests) is ready, implement it to the environment test

**Comment by ballinette** [comment] 2017-03-29 14:27
duplicate of https://github.com/kuzzleio/kuzzle-private-backlog/issues/40

**Closed by ballinette** 2017-03-29 14:27 UTC
Labels: blocked, duplicate, feature-request
